### PR TITLE
feat: add Blast chain

### PR DESCRIPTION
**Pull request by myz1237**
https://lifi.atlassian.net/browse/LF-8287

### CODE REVIEW

**Review by mathiasmoeller — CHANGES_REQUESTED** [review]
For Mantle you had to add the token information in later PRs, do we want to do all together in one go?
image

**Comment by myz1237** [comment]
Thanks for your reminder. Blast used ETH as gas token rather than so-called Blast token.

**Comment by myz1237** [comment]
I will add Blast tokens in data-types, not here. Here we only have basic token

**Review by mathiasmoeller — APPROVED** [review]
Coolio 👌

**Pull request merged**
