### PR TITLE
chore: update Action fromAddress property to required

### PR DESCRIPTION
**Pull request by rialco**

### CODE REVIEW

**Review by mathiasmoeller — COMMENTED** [review]
first of all this is not a chore, this is a breaking change

**Review by mathiasmoeller — COMMENTED** [review]
We can not do this, it's a breaking change. We can only do this internally in the Backend if we need this

**Comment by chybisov** [comment]
@mathiasmoeller This won't break anything on the frontend, so if you need this go for it here so we can have the same types

**Comment by mathiasmoeller** [comment]
But it could break any other partner integration. @rialco can we close this PR?

**Comment by chybisov** [comment]
> But it could break any other partner integration. @rialco can we close this PR?

Which one? SDK v3 is still in alpha, and v2 uses types v9

**Comment by mathiasmoeller** [comment]
People using the API directly. If they don't pass the `fromAddress` in the `Action` yet it will break

**Comment by myz1237** [comment]
is it safe to discard it?

**Pull request closed without merging**
