### PR TITLE
chore: add integrator on FullStatusData

### PR DESCRIPTION
**Pull request by rialco**

### CODE REVIEW

**Review by melianessa — APPROVED** [review]

**Review by chybisov — APPROVED** [review]

**Review by maxklenk — APPROVED** [review]

**Comment by mindrunner** [comment]
Isn't this a breaking change? Why do we release as a patch then? Why would we not respect `semver` on a public package?

**Comment by chybisov** [comment]
@mindrunner, yes, this should have been a `feat:` instead of `chore:`. However, it is not a breaking change.

**Comment by chybisov** [comment]
Oh, I see, it can be a breaking change for BE. Let's merge this https://github.com/lifinance/types/pull/183 before we can make any breaking changes releases 🙂

**Comment by mindrunner** [comment]
> Oh, I see, it can be a breaking change for BE. Let's merge this #183 before we can make any breaking changes releases 🙂

This comment is unnecessary, off topic, plus for me it sounds a bit passive aggressive. I have no clue what you want to tell me with that. This change was discussed yesterday in backend daily as a possible breaking change and should also treated like one.

**Comment by chybisov** [comment]
@mindrunner I don't know where you found passive aggression there, and your comment sounds offensive to me. I was referring to a PR that needs to be addressed before making any breaking changes releases because I've already started making v10 releases in that PR, and if we release a breaking change in the main branch, it will be a major version bump from v9 to v10.

**Pull request merged**
