### PR TITLE
feat: remove insurance

### PR DESCRIPTION
**Pull request by chybisov**

### CODE REVIEW

**Review by H3xept — APPROVED** [review]

**Comment by myz1237** [comment]
Can we tag these property deprecated, rather than delete

**Comment by chybisov** [comment]
@myz1237 feel free to make the changes. Also, if we mark them as deprecated rather than removing them, please also delete `!` from the PR title so as not to make this a breaking change.

**Comment by myz1237** [comment]
@chybisov Could you please check it again? then we ship it

**Comment by chybisov** [comment]
@myz1237 looks ok to me

**Pull request merged**
